language: java

jdk:
  - openjdk8
  - openjdk11

install: /bin/true # skip gradle assemble

script: bin/go check

after_success:
  - bin/go jacocoRootReport
  - bash <(curl -s https://codecov.io/bash)
