language: java

jdk:
  - oraclejdk8

before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

install: /bin/true # skip gradle assemble

script: bin/go check

after_success:
  - bin/go jacocoRootReport
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
