spring:
    application:
        name: example-status
    jackson:
        date-format: yyyy-MM-dd'T'hh:mm:ss.sssZ
        serialization:
            indent-output: true

server:
    context-path: /
    port: 8080

management:
    context-path: /internal
    security:
        # Disable security, so we can see /internal/info etc
        enabled: false

edison:
    gracefulshutdown:
        enabled: false
    status:
        application:
            description: Example service to show how to use edison-core in your microservices
            environment: local
            group: example
            title: Example Status
        team:
            business-contact: edison-team@example.org
            name: Edison Team
            technical-contact: edison-dev@example.org
#    ldap:
#        enabled: false
#        host: ldap.example.com
#        port: 389
#        base-dn: ou=test,ou=people,dc=example,dc=org
#        rdn-identifier: uid
#        whitelisted-paths: /internal/health,/internal/status
