spring:
    application:
        name: example-status
    jackson:
        date-format: yyyy-MM-dd'T'hh:mm:ss.sssZ
        serialization:
            indent-output: true

server:
    context-path: /
    port: 8080

management:
    context-path: /internal

edison:
    gracefulshutdown:
        enabled: false
    status:
        application:
            description: Example service to show how to use edison-core in your microservices
            environment: local
            group: example
            title: Example Core
        team:
            business-contact: edison-team@example.org
            name: Edison Team
            technical-contact: edison-dev@example.org
    ldap:
        enabled: true
        host: ldap.lhotse.ov.otto.de
        port: 389
        base-dn: ou=otto,ou=people,dc=lhotse,dc=otto,dc=de
        rdn-identifier: uid
        whitelisted-paths: /internal/health,/internal/status